#------------------------------------------------------------------------------
include ../config/ProjectDef.mk
include ../config/RootDef.mk
#------------------------------------------------------------------------------

NAME          = Mosaic

headers       = EdbMosaicIO.h EdbMosaicPath.h EdbMosaic.h EdbFragmentAlignment.h 

PROJECT_LIBS  = $(PROJECT_LIBS) -lEdb -lEbase -lEdr -lEmath

#------------------------------------------------------------------------------
include ../config/TargetsDef.mk
#------------------------------------------------------------------------------
